### ISSUE TITLE
Construct to clipboard or into active document?

### ISSUE THREAD

**Issue by krlmlr** [cynkra/constructive#223]
Often, I find myself running `constructive::construct()` just to copy the result into the clipboard and paste it into a document. Can we simplify this process?

**Comment by moodymudskipper** [comment]
We might enhance construct_dump() with a special `path = "clipboard"`
Another option would be to do like reprex, copy to viewer and to clipboard, and have an addin (the addin can't consider arguments but we can set the behavior through options).

**Comment by moodymudskipper** [comment]
The feature is simple enough, as mentioned in #245 my issue is more about names and scope. I think we need to understand what reprex related features we need and then distribute them into well named functions.

I think this feature request is best as a wrapper around `construct_multi()` for flexibility, and also easier to code, here's a way to do it: 

```{r}
construct_to_reprex <- function(obj) {
 obj_code <- constructive::construct_multi(obj, check = FALSE)$code
 reprex_code <- c("reprex::reprex({", obj_code, "})")
 eval.parent(parse(text = reprex_code))
}

construct_to_reprex(dplyr::lst(cars, letters))
```

This will create the reprex below:

``` r
cars <- data.frame(
  speed = rep(
    c(4, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25),
    c(2L, 2L, 1L, 1L, 3L, 2L, 4L, 4L, 4L, 3L, 2L, 3L, 4L, 3L, 5L, 
    1L, 1L, 4L, 1L)
  ),
  dist = c(
    2, 10, 4, 22, 16, 10, 18, 26, 34, 17, 28, 14, 20, 24, 28, 26, 34, 34, 46, 26,
    36, 60, 80, 20, 26, 54, 32, 40, 32, 40, 50, 42, 56, 76, 84, 36, 46, 68, 32,
    48, 52, 56, 64, 66, 54, 70, 92, 93, 120, 85
  )
)

letters <- c(
  "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o",
  "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"
)
```

<sup>Created on 2023-11-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

If it's to paste it to a Rmd that's good, to paste it in a script it's still a bit awkward.

What do you think about having an option to set to `TRUE` so that all constructed outputs are copied to the clipboard ? I don't think I would like to make it default because I find it a bit rude to mess with people's clipboards without asking (though reprex does it), but that would be easy enough to opt in forever ?
